### PR TITLE
SQL Course

### PR DESCRIPTION
**Pull request by lizTheDeveloper**
contains two courses:
- DQL: Data Query Language
- DDL: Data Definition Language
Also contains an example insight for structural reference

todo:
- [x] add **image** to course
- [x] change **color** of course
- [ ] change **description** of course
- [ ] remove all private content used for testing (workouts/insights/topics with the same slug)
- [ ] remove all `parent`s in workouts and add them to a different PR
( tried this on private content, but the sorting algorithms fails as it has some kind of threshold ) - ping @Loopiezlol

### CODE REVIEW

**Comment by enki-hq** [comment]
404 error making request GET https://api.github.com/repos/sagelabs/content/contents/CSS/README.md: "Not Found"

**Comment by enki-hq** [comment]
404 error making request GET https://api.github.com/repos/sagelabs/content/contents/SQL/DQL/What%20is%20SQL?/what-is-an-rdbms.md: "Not Found"

**Comment by enki-hq** [comment]
Invalid section title on line 41: # Practice

**Comment by enki-hq** [comment]
Invalid section title on line 41: # Practice

**Comment by enki-hq** [comment]
Invalid section title on line 58: # Revision

**Comment by enki-hq** [comment]
404 error making request GET https://api.github.com/repos/sagelabs/content/contents/CSS/README.md: "Not Found"

**Comment by enki-hq** [comment]
404 error making request GET https://api.github.com/repos/sagelabs/content/contents/CSS/README.md: "Not Found"

**Comment by enki-hq** [comment]
end of the stream or a document separator is expected at line 1, column 7:
    name: `INSERT`, `UPDATE`, and `DELETE`
          ^

**Comment by enki-hq** [comment]
end of the stream or a document separator is expected at line 1, column 7:
    name: `INSERT`, `UPDATE`, and `DELETE`
          ^

**Comment by enki-hq** [comment]
end of the stream or a document separator is expected at line 1, column 7:
    name: `INSERT`, `UPDATE`, and `DELETE`
          ^

**Comment by Loopiezlol** [comment]
the slug rule will be failing because I merged these insights into private content
before sql release we need to delete all insights with private sql topics

**Comment by Loopiezlol** [comment]
also, ordering is kinda faulty, do we have a doc that that should reflect the structure? 
seems like a lot is changed from https://paper.dropbox.com/doc/SQL-Curriculum-MSUoUuNWTja7vavgI6Goy

**Comment by enki-hq** [comment]
Invalid section title on line 41:   1 |     1 |          0 |              1

**Comment by enki-hq** [comment]
Invalid section title on line 44:   1 |     1 |          0 |              1

**Pull request merged**
